# Form implementation generated from reading ui file 'Fullscreen_resize_pyQt6/gui/main_ui.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(609, 446)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main.sizePolicy().hasHeightForWidth())
        main.setSizePolicy(sizePolicy)
        main.setMaximumSize(QtCore.QSize(16777215, 16777215))
        main.setStyleSheet("QWidget {\n"
"    background-color:rgb(255, 85, 255);\n"
"}\n"
"\n"
"QFrame {\n"
"    color:rgb(0, 0, 0);\n"
"    background-color:rgb(85, 255, 255);\n"
"    font: 9pt \"Sans Serif Collection\";\n"
"    border-radius:30px;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color:rgb(0, 170, 255);\n"
"    border-radius:0px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color:rgb(0, 0, 255);\n"
"    color:white;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color:rgb(255, 85, 255);\n"
"    placeholder-text-color:rgb(170, 255, 255);\n"
"    color:black;\n"
"    font: 9pt \"Sans Serif Collection\";\n"
"    padding:5px;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(85, 0, 255);\n"
"    border: 2px outset rgb(0, 0, 255);\n"
"    padding: 2px;\n"
"    font: 9pt \"Sans Serif Collection\";\n"
"    font-weight: bold;\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 0, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 2px inset rgb(85, 0, 127);\n"
"    background-color: rgb(0, 0, 255);\n"
"}\n"
"\n"
"QLabel#LEmailWarn{\n"
"    color:red;\n"
"}")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout(main)
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.frame = QtWidgets.QFrame(parent=main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.LName = QtWidgets.QLabel(parent=self.frame)
        self.LName.setObjectName("LName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.LName)
        self.EditName = QtWidgets.QLineEdit(parent=self.frame)
        self.EditName.setObjectName("EditName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.EditName)
        self.LEmail = QtWidgets.QLabel(parent=self.frame)
        self.LEmail.setObjectName("LEmail")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.LEmail)
        self.EditEmail = QtWidgets.QLineEdit(parent=self.frame)
        self.EditEmail.setObjectName("EditEmail")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.EditEmail)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LEmailWarn = QtWidgets.QLabel(parent=self.frame)
        self.LEmailWarn.setText("")
        self.LEmailWarn.setObjectName("LEmailWarn")
        self.verticalLayout_2.addWidget(self.LEmailWarn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.BSave = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BSave.sizePolicy().hasHeightForWidth())
        self.BSave.setSizePolicy(sizePolicy)
        self.BSave.setMinimumSize(QtCore.QSize(100, 0))
        self.BSave.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.BSave.setObjectName("BSave")
        self.verticalLayout_2.addWidget(self.BSave, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.verticalLayout_2)
        self.verticalLayout_1.addWidget(self.frame, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.TUsers = QtWidgets.QTableWidget(parent=main)
        self.TUsers.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.TUsers.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.TUsers.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.TUsers.setRowCount(0)
        self.TUsers.setObjectName("TUsers")
        self.TUsers.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.TUsers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TUsers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TUsers.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TUsers.setHorizontalHeaderItem(3, item)
        self.TUsers.verticalHeader().setVisible(False)
        self.verticalLayout_1.addWidget(self.TUsers)
        self.verticalLayout_1.setStretch(0, 1)
        self.verticalLayout_1.setStretch(1, 3)

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Form"))
        self.LName.setText(_translate("main", "Name"))
        self.EditName.setPlaceholderText(_translate("main", "Enter  your  name"))
        self.LEmail.setText(_translate("main", "Email"))
        self.EditEmail.setPlaceholderText(_translate("main", "Enter  your  email"))
        self.BSave.setText(_translate("main", "Save"))
        item = self.TUsers.horizontalHeaderItem(0)
        item.setText(_translate("main", "ID"))
        item = self.TUsers.horizontalHeaderItem(1)
        item.setText(_translate("main", "Name"))
        item = self.TUsers.horizontalHeaderItem(2)
        item.setText(_translate("main", "Email"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main = QtWidgets.QWidget()
    ui = Ui_main()
    ui.setupUi(main)
    main.show()
    sys.exit(app.exec())
